---
name: GH Secrets
description: |
  Creates and updates your repository secrets.
  Ideal to setup some dynamic credentials in CI jobs :)
inputs:
  token:
    description: |
      Due to the scope of a token accessible in Github Actions
      context, a personal access token is required to make this action work.

      This token should be have at least `repo` scope.
  secrets:
    description: |
      key: value map where:
        key - a name of the secret, as visible in Github's secrets page
        value - a value for that secret
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.pa-token }}
branding:
  icon: "shield"
  color: "green"
