---
name: GH Secrets
description: |
  Creates and updates your repository secrets.
  Ideal to setup some dynamic credentials in CI jobs :)
inputs:
  repository:
    required: false
    description: |
      Repository where secrets ought to be updated. This is an optional
      parameter and, if not set, it defaults to current repository.
  token:
    required: true
    description: |
      Due to the scope of a token accessible in Github Actions
      context, a personal access token is required to make this action work.

      This token should be have at least `repo` scope.
runs:
  using: docker
  image: Dockerfile

branding:
  icon: "shield"
  color: "green"
